### ISSUE TITLE
Github token

### ISSUE THREAD

**Issue by hanrattyjen** [bazaarvoice/pr_releasenotes#7]
Hey, am trying to test out releasenotes on one of our projects and I keep getting a 404 not found error.
It seems to be coming from access to the github api, but I'm using my current, working git token, so unsure why it won't let me in.

**Comment by hanrattyjen** [comment]
Resolved. Looks like a permissions error so I added a new personal token with just the minimum permissions needed.

![image](https://user-images.githubusercontent.com/14311459/58472122-70fb0d00-813d-11e9-8152-61a6f4074c24.png)

**Comment by arvindth** [comment]
@hanrattyjen glad it worked out. I see you've also checked the user permissions which you definitely don't need. For security, you may want to remove those.
